/* ═══════════════════════════════════════════════════════════════════════════
   PDF Export Utility — Velanova AI Governance Engine
   Client-side PDF generation using jsPDF + jspdf-autotable + html2canvas
   ═══════════════════════════════════════════════════════════════════════════ */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import html2canvas from 'html2canvas';

/* ── Brand colours (matched to Tailwind theme) ────────────────────────── */
const BRAND = {
  dark:    [8, 8, 8]       as [number, number, number],
  accent:  [99, 102, 241]  as [number, number, number],   // indigo-500
  white:   [255, 255, 255] as [number, number, number],
  muted:   [113, 113, 122] as [number, number, number],   // zinc-500
  surface: [24, 24, 27]    as [number, number, number],   // zinc-900
  green:   [34, 197, 94]   as [number, number, number],
  red:     [239, 68, 68]   as [number, number, number],
  amber:   [245, 158, 11]  as [number, number, number],
};

/* ── Types ────────────────────────────────────────────────────────────── */
export interface PDFSection {
  type: 'heading' | 'text' | 'table' | 'stats' | 'divider' | 'chart-snapshot';
  title?: string;
  content?: string;
  /** For table sections: column headers */
  columns?: string[];
  /** For table sections: rows of data */
  rows?: string[][];
  /** For stats sections: key-value cards */
  stats?: { label: string; value: string; change?: string }[];
  /** For chart-snapshot: DOM element ID to capture */
  elementId?: string;
}

export interface PDFReportOptions {
  title: string;
  subtitle?: string;
  module: string;
  jurisdiction?: string;
  classification?: string;
  generatedBy?: string;
  sections: PDFSection[];
  /** Include data sovereignty footer */
  includeComplianceBadges?: boolean;
}

/* ── Helper: add page header & footer to every page ────────────────── */
function addPageChrome(doc: jsPDF, options: PDFReportOptions, pageNum: number, totalPages: number) {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();

  // ── Header bar ──
  doc.setFillColor(...BRAND.dark);
  doc.rect(0, 0, w, 18, 'F');
  doc.setFontSize(9);
  doc.setTextColor(...BRAND.white);
  doc.text('VELANOVA', 10, 12);
  doc.setFontSize(7);
  doc.setTextColor(...BRAND.muted);
  doc.text(`AI Adoption & Governance Engine`, 38, 12);

  // Classification badge (top right)
  const classification = options.classification || 'OFFICIAL';
  doc.setFontSize(7);
  doc.setTextColor(...BRAND.accent);
  doc.text(classification, w - 10, 12, { align: 'right' });

  // ── Footer bar ──
  doc.setFillColor(...BRAND.dark);
  doc.rect(0, h - 14, w, 14, 'F');
  doc.setFontSize(6);
  doc.setTextColor(...BRAND.muted);
  doc.text(`Generated: ${new Date().toLocaleString('en-GB')} | Module: ${options.module}`, 10, h - 5);
  doc.text(`Page ${pageNum} of ${totalPages}`, w - 10, h - 5, { align: 'right' });

  if (options.includeComplianceBadges !== false) {
    doc.text('LOCAL STORAGE ONLY | AES-256 | GDPR COMPLIANT', w / 2, h - 5, { align: 'center' });
  }
}

/* ── Main export function ─────────────────────────────────────────── */
export async function generatePDFReport(options: PDFReportOptions): Promise<void> {
  const doc = new jsPDF('p', 'mm', 'a4');
  const w = doc.internal.pageSize.getWidth();  // 210
  const margin = 14;
  let y = 0;

  // ── Cover / Title block ──
  doc.setFillColor(...BRAND.dark);
  doc.rect(0, 0, w, 65, 'F');

  // Accent line
  doc.setFillColor(...BRAND.accent);
  doc.rect(0, 65, w, 1.5, 'F');

  // Logo text
  doc.setFontSize(11);
  doc.setTextColor(...BRAND.accent);
  doc.text('VELANOVA', margin, 18);

  // Title
  doc.setFontSize(22);
  doc.setTextColor(...BRAND.white);
  doc.text(options.title, margin, 36);

  // Subtitle
  if (options.subtitle) {
    doc.setFontSize(10);
    doc.setTextColor(...BRAND.muted);
    doc.text(options.subtitle, margin, 46);
  }

  // Meta info
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.muted);
  const meta = [
    `Module: ${options.module}`,
    options.jurisdiction ? `Jurisdiction: ${options.jurisdiction}` : '',
    `Date: ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`,
    options.generatedBy ? `Generated by: ${options.generatedBy}` : 'Generated by: Velanova AI Engine',
  ].filter(Boolean).join('   |   ');
  doc.text(meta, margin, 57);

  y = 75; // Start content below cover

  // ── Process sections ──
  for (const section of options.sections) {
    // Check if we need a new page (leave 30mm for footer)
    if (y > 260) {
      doc.addPage();
      y = 25;
    }

    switch (section.type) {
      case 'heading': {
        doc.setFontSize(13);
        doc.setTextColor(...BRAND.white);
        doc.setFillColor(...BRAND.surface);
        doc.roundedRect(margin - 2, y - 4, w - (margin * 2) + 4, 10, 1, 1, 'F');
        doc.text(section.title || '', margin, y + 3);
        y += 15;
        break;
      }

      case 'text': {
        doc.setFontSize(9);
        doc.setTextColor(180, 180, 185);
        const lines = doc.splitTextToSize(section.content || '', w - margin * 2);
        doc.text(lines, margin, y);
        y += lines.length * 4.5 + 4;
        break;
      }

      case 'stats': {
        if (!section.stats?.length) break;
        const cardW = (w - margin * 2 - (section.stats.length - 1) * 4) / section.stats.length;
        section.stats.forEach((stat, i) => {
          const cx = margin + i * (cardW + 4);
          doc.setFillColor(...BRAND.surface);
          doc.roundedRect(cx, y, cardW, 20, 2, 2, 'F');

          doc.setFontSize(7);
          doc.setTextColor(...BRAND.muted);
          doc.text(stat.label, cx + 3, y + 6);

          doc.setFontSize(14);
          doc.setTextColor(...BRAND.white);
          doc.text(stat.value, cx + 3, y + 15);

          if (stat.change) {
            const isPositive = stat.change.startsWith('+') || stat.change.toLowerCase().includes('up');
            doc.setFontSize(6);
            doc.setTextColor(...(isPositive ? BRAND.green : BRAND.red));
            doc.text(stat.change, cx + cardW - 3, y + 6, { align: 'right' });
          }
        });
        y += 28;
        break;
      }

      case 'table': {
        if (!section.columns || !section.rows) break;
        autoTable(doc, {
          startY: y,
          head: [section.columns],
          body: section.rows,
          margin: { left: margin, right: margin },
          styles: {
            fontSize: 7.5,
            cellPadding: 2.5,
            textColor: [200, 200, 205],
            lineWidth: 0,
          },
          headStyles: {
            fillColor: BRAND.surface,
            textColor: BRAND.accent,
            fontStyle: 'bold',
            fontSize: 7.5,
          },
          alternateRowStyles: {
            fillColor: [15, 15, 18],
          },
          bodyStyles: {
            fillColor: [11, 11, 11],
          },
          theme: 'plain',
          didDrawPage: () => {
            // pages drawn by autoTable get chrome later
          },
        });
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        y = (doc as any).lastAutoTable?.finalY + 8 || y + 30;
        break;
      }

      case 'chart-snapshot': {
        if (!section.elementId) break;
        const element = document.getElementById(section.elementId);
        if (!element) break;
        try {
          const canvas = await html2canvas(element, {
            backgroundColor: '#0b0b0b',
            scale: 2,
            logging: false,
            useCORS: true,
          });
          const imgData = canvas.toDataURL('image/png');
          const imgW = w - margin * 2;
          const imgH = (canvas.height / canvas.width) * imgW;

          if (y + imgH > 260) {
            doc.addPage();
            y = 25;
          }

          if (section.title) {
            doc.setFontSize(10);
            doc.setTextColor(...BRAND.white);
            doc.text(section.title, margin, y);
            y += 6;
          }

          doc.addImage(imgData, 'PNG', margin, y, imgW, imgH);
          y += imgH + 8;
        } catch {
          doc.setFontSize(8);
          doc.setTextColor(...BRAND.red);
          doc.text('[Chart capture failed]', margin, y);
          y += 8;
        }
        break;
      }

      case 'divider': {
        doc.setDrawColor(...BRAND.surface);
        doc.setLineWidth(0.3);
        doc.line(margin, y, w - margin, y);
        y += 6;
        break;
      }
    }
  }

  // ── Apply page chrome to all pages ──
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addPageChrome(doc, options, i, totalPages);
  }

  // ── Save ──
  const filename = `Velanova_${options.module.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}

/* ── Quick export: capture a DOM section as single-page PDF ─────── */
export async function exportElementAsPDF(
  elementId: string,
  title: string,
  module: string,
): Promise<void> {
  const element = document.getElementById(elementId);
  if (!element) {
    console.error(`Element #${elementId} not found`);
    return;
  }

  const canvas = await html2canvas(element, {
    backgroundColor: '#0b0b0b',
    scale: 2,
    logging: false,
    useCORS: true,
  });

  const doc = new jsPDF('p', 'mm', 'a4');
  const w = doc.internal.pageSize.getWidth();
  const margin = 10;
  const imgW = w - margin * 2;
  const imgH = (canvas.height / canvas.width) * imgW;

  // Title
  doc.setFillColor(...BRAND.dark);
  doc.rect(0, 0, w, 22, 'F');
  doc.setFontSize(11);
  doc.setTextColor(...BRAND.accent);
  doc.text('VELANOVA', margin, 10);
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.muted);
  doc.text(`${title} — ${new Date().toLocaleDateString('en-GB')}`, margin, 17);

  doc.addImage(canvas.toDataURL('image/png'), 'PNG', margin, 26, imgW, imgH);

  // Footer
  const h = doc.internal.pageSize.getHeight();
  doc.setFillColor(...BRAND.dark);
  doc.rect(0, h - 10, w, 10, 'F');
  doc.setFontSize(6);
  doc.setTextColor(...BRAND.muted);
  doc.text(`Module: ${module} | LOCAL STORAGE ONLY | AES-256 | GDPR COMPLIANT`, w / 2, h - 4, { align: 'center' });

  const filename = `Velanova_${module.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}
